apiVersion: v1
kind: ReplicationController
metadata:
  name: mqtt-master
  labels:
    name: mqtt-master
spec:
  replicas: 1
  selector:
    name: mqtt-master
  template:
    metadata:
      labels:
        name: mqtt-master
    spec:
      containers:
      - name: master
        image: ansi/mosquitto
        ports:
        - containerPort: 1883
